# Ansible

# IP pública de la máquina puente (master)
azure_public_ip: 137.117.197.56

# IP local de la red de kubernetes de master
master_ip: 10.0.1.10

# Puerto por defecto de HAProxy
ha_proxy_port: 5446

# Puerto por defecto de HAProxy stats
haproxy_stats_port: 9000

# Imagen de haproxy a utilizar
haproxy_container_image: haproxy:1.5

# Comando de proxyjump para llegar a los hosts
ansible_ssh_common_args:  '-o "ProxyCommand ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -W %h:%p ansible@{{ azure_public_ip }}"'


# Kubernetes
kube_version: v1.20.4
token: b0f7b8.8d1767876297d85c

# 1.8.x feature: --feature-gates SelfHosting=true
init_opts: ""

# Any other additional opts you want to add..
kubeadm_opts: ""
# For example:
# kubeadm_opts: '--apiserver-cert-extra-sans "k8s.domain.com,kubernetes.domain.com"'

service_cidr: "10.96.0.0/12"
pod_network_cidr: "10.244.0.0/16"

# Network implementation
network: calico

# Change this to an appropriate interface, preferably a private network.
# For example, on DigitalOcean, you would use eth1 as that is the default private network interface.
network_interface: "eth0"

enable_dashboard: yes

# A list of insecure registries you might need to define
# insecure_registries: []
insecure_registries: ['gcr.io']

systemd_dir: /lib/systemd/system
system_env_dir: /etc/sysconfig
network_dir: /etc/kubernetes/network
kubeadmin_config: /etc/kubernetes/admin.conf
kube_addon_dir: /etc/kubernetes/addon

# temporary directory used by additional features
tmp_dir: /tmp/kubeadm-ansible-files
