---
- hosts: master
  become: no
  gather_facts: false
  tasks:
    - name: Creates directory nfsk8s
      file:
        path: /nfsk8s
        state: directory
      become: true
    - name: "Create mountpoint on NFS Server"
      lineinfile:
        path: /etc/exports
        line: "/nfsk8s 10.0.1.21(rw) 10.0.1.22(rw)"
      become: true
    - name: "Publish exports"
      shell:  exportfs -ra
      become: true
    - name: "Copy deployment file"
      copy:
        content: |
          # Create a pod that reads and writes to the
          # NFS server via an NFS volume.

          kind: Pod
          apiVersion: v1
          metadata:
            name: pod-using-nfs
          spec:
            # Add the server as an NFS volume for the pod
            volumes:
              - name: nfs-volume
                nfs: 
                  # URL for the NFS server
                  server: 10.0.1.10
                  path: /nfsk8s

            # In this container, we'll mount the NFS volume
            # and write the date to a file inside it.
            containers:
              - name: app
                image: alpine

                # Mount the NFS volume in the container
                volumeMounts:
                  - name: nfs-volume
                    mountPath: /var/nfs

                # Write to a file inside our NFS
                command: ["/bin/sh"]
                args: ["-c", "while true; do date >> /var/nfs/dates.txt; sleep 5; done"]
        dest: /tmp/deployment_app_test.yaml
    - name: Apply deployment file
      shell: kubectl apply -f /tmp/deployment_app_test.yaml
