---

- name: Check if kubelet.conf exists
  stat:
    path: "/etc/kubernetes/kubelet.conf"
  register: kubelet_conf

- name: Join to cluster if needed
  include_tasks: join.yml
  when: not kubelet_conf.stat.exists

- name: Copy systemd modified kubelet.service
  copy:
    src: kubelet.service
    dest: /usr/lib/systemd/system/kubelet.service
  
- systemd:
    daemon_reload: yes


- name: Enable and check kubelet service
  systemd:
    name: kubelet
    daemon_reload: yes
    state: started
    enabled: yes
